CREATE TABLE USER(
    ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(100),
    ACCOUNT_ID VARCHAR(50),
    TOKEN CHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    BIO VARCHAR(256)
);
